### ISSUE TITLE
Mismatch in documentation vs code for authentication

### ISSUE THREAD

**Issue by alexmurray** [tarsius/ghub#18]
The README.md and the comments in ghub.el say to use 'password' in the authinfo.gpg however the code in ghub.el uses 'secret' - so if 'password' is used then it fails to retrieve the token, however if 'secret' is used in authinfo then it works as expected.

README.md and ghub.el should be updated to resolve this.

**Comment by tarsius** [comment]
Hm, actually this seems to work for me. In `~/.authinfo.gpg` I use `password`, but `auth-source-search` never-the-less returns a plist containing a key `:secret`, but no `:password` key.

If I replace `password` with `secret` in the file, then it also works. Maybe it doesn't work for you because you use an older Emacs?

Documentation is sparse, but both `man 5 netrc` and `info (auth-source)` say that `password` should be used as key, without mentioning `secret`.
